Update trufflehog.yml

diff --git a/.github/workflows/trufflehog.yml b/.github/workflows/trufflehog.yml
--- a/.github/workflows/trufflehog.yml
+++ b/.github/workflows/trufflehog.yml
@@ -25,7 +25,7 @@ jobs:
         run: pip install trufflehog
         
       - name: Run Secret Scanning
-        run: trufflehog --entropy=True --json ${{ github.workspace }} > secret_scan.json
+        run: trufflehog --entropy=True --json ${{ github.workspace }} > secret_scan.json || echo "::error::Secret scanning failed"
         
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
